language: erlang
otp_release:
  - 17.0-rc1
  - R16B03-1
before_install:
  - git clone -b v0.12.4 --depth 1 git://github.com/elixir-lang/elixir
  - make -C elixir
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
script:
  - mix test
