language: erlang
otp_release:
  - 17.0
before_install:
  - git clone -b v0.13.3 --depth 1 git://github.com/elixir-lang/elixir
  - make -C elixir
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
script:
  - mix test
